resources:
- repo: self
  clean: true
queue:
  name: Hosted VS2017
steps:
- task: PowerShell@2
  inputs:
    filePath: scripts/setVersion.ps1
- task: stevedower.python.BuildWheel.BuildWheel@1
  inputs:
    setuppy: 'src/noelbundick/setup.py'
    signcmd: 'bdist_wheel'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
    publishLocation: Container